#!/bin/bash

# Auto-Build Environment Setup
# Project: Desktop Jira Clone with OneNote Integration
# Generated by Planner Agent - Session 1

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Desktop Jira Clone with OneNote Integration"
echo "========================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$PROJECT_ROOT"

echo -e "${BLUE}Project Root:${NC} $PROJECT_ROOT"
echo ""

# Function to wait for a service to be ready
wait_for_service() {
    local port=$1
    local name=$2
    local max_attempts=${3:-30}
    local count=0

    echo -e "${YELLOW}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max_attempts ]; then
            echo -e "${RED}ERROR: $name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
        echo -n "."
    done
    echo ""
    echo -e "${GREEN}$name is ready on port $port${NC}"
}

# Function to check if a directory exists
check_directory() {
    local dir=$1
    local name=$2
    if [ ! -d "$dir" ]; then
        echo -e "${RED}ERROR: $name directory not found at $dir${NC}"
        echo -e "${YELLOW}Please run the coder agent first to create the project structure${NC}"
        return 1
    fi
    echo -e "${GREEN}Found $name at $dir${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "========================================"
echo "Pre-flight Checks"
echo "========================================"

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}ERROR: Node.js is not installed${NC}"
    echo "Please install Node.js 18+ from https://nodejs.org/"
    exit 1
fi
echo -e "${GREEN}Node.js:${NC} $(node --version)"

# Check for npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}ERROR: npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}npm:${NC} $(npm --version)"

# Check for Python
if ! command -v python &> /dev/null && ! command -v python3 &> /dev/null; then
    echo -e "${RED}ERROR: Python is not installed${NC}"
    echo "Please install Python 3.11+ from https://python.org/"
    exit 1
fi
PYTHON_CMD=$(command -v python3 || command -v python)
echo -e "${GREEN}Python:${NC} $($PYTHON_CMD --version)"

# Check for pip
if ! command -v pip &> /dev/null && ! command -v pip3 &> /dev/null; then
    echo -e "${RED}ERROR: pip is not installed${NC}"
    exit 1
fi
PIP_CMD=$(command -v pip3 || command -v pip)
echo -e "${GREEN}pip:${NC} $($PIP_CMD --version)"

# Check for ODBC Driver (optional but recommended)
if command -v odbcinst &> /dev/null; then
    if odbcinst -q -d -n "ODBC Driver 17 for SQL Server" &> /dev/null; then
        echo -e "${GREEN}ODBC Driver 17 for SQL Server: Installed${NC}"
    else
        echo -e "${YELLOW}WARNING: ODBC Driver 17 for SQL Server not found${NC}"
        echo "Database connections may fail. Install from:"
        echo "https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server"
    fi
else
    echo -e "${YELLOW}WARNING: Cannot verify ODBC driver installation${NC}"
fi

# ============================================
# CHECK PROJECT STRUCTURE
# ============================================

echo ""
echo "========================================"
echo "Checking Project Structure"
echo "========================================"

BACKEND_DIR="$PROJECT_ROOT/fastapi-backend"
FRONTEND_DIR="$PROJECT_ROOT/electron-app"
TESTS_DIR="$PROJECT_ROOT/tests"

# Check if directories exist (they may not until coder agent runs)
if [ -d "$BACKEND_DIR" ]; then
    echo -e "${GREEN}Backend directory found${NC}"
    BACKEND_EXISTS=true
else
    echo -e "${YELLOW}Backend directory not found - will be created by coder agent${NC}"
    BACKEND_EXISTS=false
fi

if [ -d "$FRONTEND_DIR" ]; then
    echo -e "${GREEN}Frontend directory found${NC}"
    FRONTEND_EXISTS=true
else
    echo -e "${YELLOW}Frontend directory not found - will be created by coder agent${NC}"
    FRONTEND_EXISTS=false
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "========================================"
echo "Installing Dependencies"
echo "========================================"

# Backend dependencies
if [ "$BACKEND_EXISTS" = true ] && [ -f "$BACKEND_DIR/requirements.txt" ]; then
    echo -e "${BLUE}Installing Python dependencies...${NC}"
    cd "$BACKEND_DIR"
    $PIP_CMD install -r requirements.txt
    cd "$PROJECT_ROOT"
    echo -e "${GREEN}Python dependencies installed${NC}"
else
    echo -e "${YELLOW}Skipping Python dependencies (no requirements.txt yet)${NC}"
fi

# Frontend dependencies
if [ "$FRONTEND_EXISTS" = true ] && [ -f "$FRONTEND_DIR/package.json" ]; then
    echo -e "${BLUE}Installing Node.js dependencies...${NC}"
    cd "$FRONTEND_DIR"
    npm install
    cd "$PROJECT_ROOT"
    echo -e "${GREEN}Node.js dependencies installed${NC}"
else
    echo -e "${YELLOW}Skipping Node.js dependencies (no package.json yet)${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "========================================"
echo "Starting Services"
echo "========================================"

# Start Backend (FastAPI)
if [ "$BACKEND_EXISTS" = true ] && [ -f "$BACKEND_DIR/app/main.py" ]; then
    echo -e "${BLUE}Starting FastAPI backend on port 8000...${NC}"
    cd "$BACKEND_DIR"
    uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &
    BACKEND_PID=$!
    cd "$PROJECT_ROOT"

    # Wait for backend to be ready
    wait_for_service 8000 "FastAPI Backend" 60
else
    echo -e "${YELLOW}Skipping backend startup (app/main.py not found)${NC}"
    BACKEND_PID=""
fi

# Start Frontend (Electron)
if [ "$FRONTEND_EXISTS" = true ] && [ -f "$FRONTEND_DIR/package.json" ]; then
    echo -e "${BLUE}Starting Electron app in development mode...${NC}"
    cd "$FRONTEND_DIR"
    npm run dev &
    FRONTEND_PID=$!
    cd "$PROJECT_ROOT"
    echo -e "${GREEN}Electron app starting...${NC}"
else
    echo -e "${YELLOW}Skipping frontend startup (package.json not found)${NC}"
    FRONTEND_PID=""
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo -e "${GREEN}Services:${NC}"
echo "  Backend API:    http://localhost:8000"
echo "  API Docs:       http://localhost:8000/docs"
echo "  Electron App:   Running in development mode"
echo ""
echo -e "${GREEN}External Infrastructure:${NC}"
echo "  SQL Server:     10.18.138.240 (DB: PMDB)"
echo "  MinIO API:      http://10.18.136.10:9000"
echo "  MinIO Console:  http://10.18.136.10:9001"
echo ""
echo -e "${GREEN}Process IDs:${NC}"
if [ -n "$BACKEND_PID" ]; then
    echo "  Backend PID:    $BACKEND_PID"
fi
if [ -n "$FRONTEND_PID" ]; then
    echo "  Frontend PID:   $FRONTEND_PID"
fi
echo ""
echo -e "${YELLOW}To stop services:${NC}"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo -e "${YELLOW}To run tests:${NC}"
echo "  Backend:  cd fastapi-backend && pytest tests/ -v"
echo "  E2E:      cd tests && npx playwright test"
echo ""
echo "========================================"
echo "Happy coding!"
echo "========================================"

# Keep script running to maintain background processes
if [ -n "$BACKEND_PID" ] || [ -n "$FRONTEND_PID" ]; then
    echo ""
    echo "Press Ctrl+C to stop all services..."

    # Trap SIGINT to clean up
    trap "echo ''; echo 'Stopping services...'; kill $BACKEND_PID $FRONTEND_PID 2>/dev/null; exit 0" INT

    # Wait for processes
    wait
fi
