"""initial_schema

Revision ID: aa2fc27435bc
Revises: 
Create Date: 2026-01-17 15:32:39.158458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'aa2fc27435bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_table('Applications',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Applications_name'), 'Applications', ['name'], unique=False)
    op.create_index(op.f('ix_Applications_owner_id'), 'Applications', ['owner_id'], unique=False)
    op.create_table('Notifications',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Notifications_created_at'), 'Notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_Notifications_entity_id'), 'Notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_Notifications_entity_type'), 'Notifications', ['entity_type'], unique=False)
    op.create_index(op.f('ix_Notifications_is_read'), 'Notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_Notifications_type'), 'Notifications', ['type'], unique=False)
    op.create_index(op.f('ix_Notifications_user_id'), 'Notifications', ['user_id'], unique=False)
    op.create_table('Notes',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('application_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('parent_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('created_by', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tab_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['Applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['Users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['parent_id'], ['Notes.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Notes_application_id'), 'Notes', ['application_id'], unique=False)
    op.create_index(op.f('ix_Notes_created_by'), 'Notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_Notes_parent_id'), 'Notes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_Notes_title'), 'Notes', ['title'], unique=False)
    op.create_table('Projects',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('application_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['Applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Projects_application_id'), 'Projects', ['application_id'], unique=False)
    op.create_index(op.f('ix_Projects_key'), 'Projects', ['key'], unique=False)
    op.create_index(op.f('ix_Projects_name'), 'Projects', ['name'], unique=False)
    op.create_table('Tasks',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('project_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('assignee_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('reporter_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('parent_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('sprint_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('task_key', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['Users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['parent_id'], ['Tasks.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['Users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tasks_assignee_id'), 'Tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_Tasks_parent_id'), 'Tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_Tasks_project_id'), 'Tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_Tasks_reporter_id'), 'Tasks', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_Tasks_sprint_id'), 'Tasks', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_Tasks_status'), 'Tasks', ['status'], unique=False)
    op.create_index(op.f('ix_Tasks_task_key'), 'Tasks', ['task_key'], unique=True)
    op.create_table('Attachments',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('minio_bucket', sa.String(length=100), nullable=True),
    sa.Column('minio_key', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('task_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('note_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('uploaded_by', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['Notes.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['task_id'], ['Tasks.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['Users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Attachments_entity_id'), 'Attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_Attachments_entity_type'), 'Attachments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_Attachments_note_id'), 'Attachments', ['note_id'], unique=False)
    op.create_index(op.f('ix_Attachments_task_id'), 'Attachments', ['task_id'], unique=False)
    op.create_index(op.f('ix_Attachments_uploaded_by'), 'Attachments', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Attachments_uploaded_by'), table_name='Attachments')
    op.drop_index(op.f('ix_Attachments_task_id'), table_name='Attachments')
    op.drop_index(op.f('ix_Attachments_note_id'), table_name='Attachments')
    op.drop_index(op.f('ix_Attachments_entity_type'), table_name='Attachments')
    op.drop_index(op.f('ix_Attachments_entity_id'), table_name='Attachments')
    op.drop_table('Attachments')
    op.drop_index(op.f('ix_Tasks_task_key'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_status'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_sprint_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_reporter_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_project_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_parent_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_assignee_id'), table_name='Tasks')
    op.drop_table('Tasks')
    op.drop_index(op.f('ix_Projects_name'), table_name='Projects')
    op.drop_index(op.f('ix_Projects_key'), table_name='Projects')
    op.drop_index(op.f('ix_Projects_application_id'), table_name='Projects')
    op.drop_table('Projects')
    op.drop_index(op.f('ix_Notes_title'), table_name='Notes')
    op.drop_index(op.f('ix_Notes_parent_id'), table_name='Notes')
    op.drop_index(op.f('ix_Notes_created_by'), table_name='Notes')
    op.drop_index(op.f('ix_Notes_application_id'), table_name='Notes')
    op.drop_table('Notes')
    op.drop_index(op.f('ix_Notifications_user_id'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_type'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_is_read'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_entity_type'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_entity_id'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_created_at'), table_name='Notifications')
    op.drop_table('Notifications')
    op.drop_index(op.f('ix_Applications_owner_id'), table_name='Applications')
    op.drop_index(op.f('ix_Applications_name'), table_name='Applications')
    op.drop_table('Applications')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
