"""initial_postgresql_schema

Revision ID: 26b648a3dc17
Revises: 
Create Date: 2026-01-26 11:18:55.868031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b648a3dc17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Users table first (no dependencies)
    op.create_table('Users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)

    # Create Applications table (depends on Users)
    op.create_table('Applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Applications_name'), 'Applications', ['name'], unique=False)
    op.create_index(op.f('ix_Applications_owner_id'), 'Applications', ['owner_id'], unique=False)

    # Create Projects table WITHOUT circular FK to TaskStatuses (will add later)
    op.create_table('Projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('project_owner_user_id', sa.UUID(), nullable=True),
    sa.Column('derived_status_id', sa.UUID(), nullable=True),
    sa.Column('override_status_id', sa.UUID(), nullable=True),
    sa.Column('override_reason', sa.String(length=500), nullable=True),
    sa.Column('override_by_user_id', sa.UUID(), nullable=True),
    sa.Column('override_expires_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['Applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['Users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['override_by_user_id'], ['Users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_owner_user_id'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Projects_application_id'), 'Projects', ['application_id'], unique=False)
    op.create_index(op.f('ix_Projects_created_by'), 'Projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_Projects_derived_status_id'), 'Projects', ['derived_status_id'], unique=False)
    op.create_index(op.f('ix_Projects_key'), 'Projects', ['key'], unique=False)
    op.create_index(op.f('ix_Projects_name'), 'Projects', ['name'], unique=False)
    op.create_index(op.f('ix_Projects_override_by_user_id'), 'Projects', ['override_by_user_id'], unique=False)
    op.create_index(op.f('ix_Projects_override_status_id'), 'Projects', ['override_status_id'], unique=False)
    op.create_index(op.f('ix_Projects_project_owner_user_id'), 'Projects', ['project_owner_user_id'], unique=False)

    # Create TaskStatuses table (depends on Projects)
    op.create_table('TaskStatuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TaskStatuses_project_id'), 'TaskStatuses', ['project_id'], unique=False)

    # Add deferred foreign keys from Projects to TaskStatuses (circular reference)
    # These are added after TaskStatuses table exists due to circular dependency
    # In normal app flow: Project created with NULL → TaskStatuses created → status updated
    op.create_foreign_key(
        'fk_Projects_derived_status_id',
        'Projects', 'TaskStatuses',
        ['derived_status_id'], ['id'],
        ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_Projects_override_status_id',
        'Projects', 'TaskStatuses',
        ['override_status_id'], ['id'],
        ondelete='SET NULL'
    )

    op.create_table('Notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Notifications_created_at'), 'Notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_Notifications_entity_id'), 'Notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_Notifications_entity_type'), 'Notifications', ['entity_type'], unique=False)
    op.create_index(op.f('ix_Notifications_is_read'), 'Notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_Notifications_type'), 'Notifications', ['type'], unique=False)
    op.create_index(op.f('ix_Notifications_user_id'), 'Notifications', ['user_id'], unique=False)
    op.create_table('ProjectAssignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ProjectAssignments_assigned_by'), 'ProjectAssignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_ProjectAssignments_created_at'), 'ProjectAssignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_ProjectAssignments_project_id'), 'ProjectAssignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_ProjectAssignments_user_id'), 'ProjectAssignments', ['user_id'], unique=False)
    op.create_table('ProjectMembers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['Users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='UQ_ProjectMembers_Project_User')
    )
    op.create_index(op.f('ix_ProjectMembers_added_by_user_id'), 'ProjectMembers', ['added_by_user_id'], unique=False)
    op.create_index(op.f('ix_ProjectMembers_created_at'), 'ProjectMembers', ['created_at'], unique=False)
    op.create_index(op.f('ix_ProjectMembers_project_id'), 'ProjectMembers', ['project_id'], unique=False)
    op.create_index('ix_ProjectMembers_project_role', 'ProjectMembers', ['project_id', 'role'], unique=False)
    op.create_index(op.f('ix_ProjectMembers_user_id'), 'ProjectMembers', ['user_id'], unique=False)
    op.create_table('ProjectTaskStatusAgg',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('todo_tasks', sa.Integer(), nullable=False),
    sa.Column('active_tasks', sa.Integer(), nullable=False),
    sa.Column('review_tasks', sa.Integer(), nullable=False),
    sa.Column('issue_tasks', sa.Integer(), nullable=False),
    sa.Column('done_tasks', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('Tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sprint_id', sa.UUID(), nullable=True),
    sa.Column('task_status_id', sa.UUID(), nullable=True),
    sa.Column('task_key', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('task_rank', sa.String(length=50), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('checklist_total', sa.Integer(), nullable=False),
    sa.Column('checklist_done', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['Users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['Tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['Users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_status_id'], ['TaskStatuses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tasks_assignee_id'), 'Tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_Tasks_parent_id'), 'Tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_Tasks_project_id'), 'Tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_Tasks_reporter_id'), 'Tasks', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_Tasks_sprint_id'), 'Tasks', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_Tasks_status'), 'Tasks', ['status'], unique=False)
    op.create_index(op.f('ix_Tasks_task_key'), 'Tasks', ['task_key'], unique=True)
    op.create_index(op.f('ix_Tasks_task_status_id'), 'Tasks', ['task_status_id'], unique=False)
    op.create_table('Checklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['Tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Checklists_task_id'), 'Checklists', ['task_id'], unique=False)
    op.create_table('Comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['Tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Comments_author_id'), 'Comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_Comments_task_id'), 'Comments', ['task_id'], unique=False)
    op.create_table('Invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('inviter_id', sa.UUID(), nullable=False),
    sa.Column('invitee_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['Applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_id'], ['Users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Invitations_application_id'), 'Invitations', ['application_id'], unique=False)
    op.create_index(op.f('ix_Invitations_created_at'), 'Invitations', ['created_at'], unique=False)
    op.create_index(op.f('ix_Invitations_invitee_id'), 'Invitations', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_Invitations_inviter_id'), 'Invitations', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_Invitations_role'), 'Invitations', ['role'], unique=False)
    op.create_index(op.f('ix_Invitations_status'), 'Invitations', ['status'], unique=False)
    op.create_index('ix_invitations_app_invitee_status', 'Invitations', ['application_id', 'invitee_id', 'status'], unique=False)
    op.create_index('ix_invitations_invitee_status_created', 'Invitations', ['invitee_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_invitations_inviter_status_created', 'Invitations', ['inviter_id', 'status', 'created_at'], unique=False)
    op.create_table('Notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tab_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['Applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['Users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['Notes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Notes_application_id'), 'Notes', ['application_id'], unique=False)
    op.create_index(op.f('ix_Notes_created_by'), 'Notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_Notes_parent_id'), 'Notes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_Notes_title'), 'Notes', ['title'], unique=False)
    op.create_table('ApplicationMembers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invitation_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['Applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitation_id'], ['Invitations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ApplicationMembers_application_id'), 'ApplicationMembers', ['application_id'], unique=False)
    op.create_index(op.f('ix_ApplicationMembers_created_at'), 'ApplicationMembers', ['created_at'], unique=False)
    op.create_index(op.f('ix_ApplicationMembers_invitation_id'), 'ApplicationMembers', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_ApplicationMembers_role'), 'ApplicationMembers', ['role'], unique=False)
    op.create_index(op.f('ix_ApplicationMembers_user_id'), 'ApplicationMembers', ['user_id'], unique=False)
    op.create_table('Attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('minio_bucket', sa.String(length=100), nullable=True),
    sa.Column('minio_key', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('note_id', sa.UUID(), nullable=True),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['Comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['Notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['Tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Attachments_comment_id'), 'Attachments', ['comment_id'], unique=False)
    op.create_index(op.f('ix_Attachments_entity_id'), 'Attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_Attachments_entity_type'), 'Attachments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_Attachments_note_id'), 'Attachments', ['note_id'], unique=False)
    op.create_index(op.f('ix_Attachments_task_id'), 'Attachments', ['task_id'], unique=False)
    op.create_index(op.f('ix_Attachments_uploaded_by'), 'Attachments', ['uploaded_by'], unique=False)
    op.create_table('ChecklistItems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['Checklists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ChecklistItems_checklist_id'), 'ChecklistItems', ['checklist_id'], unique=False)
    op.create_table('Mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['Comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='UX_Mentions_Comment_User')
    )
    op.create_index(op.f('ix_Mentions_comment_id'), 'Mentions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_Mentions_user_id'), 'Mentions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop deferred foreign keys first (circular reference)
    op.drop_constraint('fk_Projects_derived_status_id', 'Projects', type_='foreignkey')
    op.drop_constraint('fk_Projects_override_status_id', 'Projects', type_='foreignkey')

    op.drop_index(op.f('ix_Mentions_user_id'), table_name='Mentions')
    op.drop_index(op.f('ix_Mentions_comment_id'), table_name='Mentions')
    op.drop_table('Mentions')
    op.drop_index(op.f('ix_ChecklistItems_checklist_id'), table_name='ChecklistItems')
    op.drop_table('ChecklistItems')
    op.drop_index(op.f('ix_Attachments_uploaded_by'), table_name='Attachments')
    op.drop_index(op.f('ix_Attachments_task_id'), table_name='Attachments')
    op.drop_index(op.f('ix_Attachments_note_id'), table_name='Attachments')
    op.drop_index(op.f('ix_Attachments_entity_type'), table_name='Attachments')
    op.drop_index(op.f('ix_Attachments_entity_id'), table_name='Attachments')
    op.drop_index(op.f('ix_Attachments_comment_id'), table_name='Attachments')
    op.drop_table('Attachments')
    op.drop_index(op.f('ix_ApplicationMembers_user_id'), table_name='ApplicationMembers')
    op.drop_index(op.f('ix_ApplicationMembers_role'), table_name='ApplicationMembers')
    op.drop_index(op.f('ix_ApplicationMembers_invitation_id'), table_name='ApplicationMembers')
    op.drop_index(op.f('ix_ApplicationMembers_created_at'), table_name='ApplicationMembers')
    op.drop_index(op.f('ix_ApplicationMembers_application_id'), table_name='ApplicationMembers')
    op.drop_table('ApplicationMembers')
    op.drop_index(op.f('ix_Notes_title'), table_name='Notes')
    op.drop_index(op.f('ix_Notes_parent_id'), table_name='Notes')
    op.drop_index(op.f('ix_Notes_created_by'), table_name='Notes')
    op.drop_index(op.f('ix_Notes_application_id'), table_name='Notes')
    op.drop_table('Notes')
    op.drop_index('ix_invitations_inviter_status_created', table_name='Invitations')
    op.drop_index('ix_invitations_invitee_status_created', table_name='Invitations')
    op.drop_index('ix_invitations_app_invitee_status', table_name='Invitations')
    op.drop_index(op.f('ix_Invitations_status'), table_name='Invitations')
    op.drop_index(op.f('ix_Invitations_role'), table_name='Invitations')
    op.drop_index(op.f('ix_Invitations_inviter_id'), table_name='Invitations')
    op.drop_index(op.f('ix_Invitations_invitee_id'), table_name='Invitations')
    op.drop_index(op.f('ix_Invitations_created_at'), table_name='Invitations')
    op.drop_index(op.f('ix_Invitations_application_id'), table_name='Invitations')
    op.drop_table('Invitations')
    op.drop_index(op.f('ix_Comments_task_id'), table_name='Comments')
    op.drop_index(op.f('ix_Comments_author_id'), table_name='Comments')
    op.drop_table('Comments')
    op.drop_index(op.f('ix_Checklists_task_id'), table_name='Checklists')
    op.drop_table('Checklists')
    op.drop_index(op.f('ix_Tasks_task_status_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_task_key'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_status'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_sprint_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_reporter_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_project_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_parent_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_assignee_id'), table_name='Tasks')
    op.drop_table('Tasks')
    op.drop_table('ProjectTaskStatusAgg')
    op.drop_index(op.f('ix_ProjectMembers_user_id'), table_name='ProjectMembers')
    op.drop_index('ix_ProjectMembers_project_role', table_name='ProjectMembers')
    op.drop_index(op.f('ix_ProjectMembers_project_id'), table_name='ProjectMembers')
    op.drop_index(op.f('ix_ProjectMembers_created_at'), table_name='ProjectMembers')
    op.drop_index(op.f('ix_ProjectMembers_added_by_user_id'), table_name='ProjectMembers')
    op.drop_table('ProjectMembers')
    op.drop_index(op.f('ix_ProjectAssignments_user_id'), table_name='ProjectAssignments')
    op.drop_index(op.f('ix_ProjectAssignments_project_id'), table_name='ProjectAssignments')
    op.drop_index(op.f('ix_ProjectAssignments_created_at'), table_name='ProjectAssignments')
    op.drop_index(op.f('ix_ProjectAssignments_assigned_by'), table_name='ProjectAssignments')
    op.drop_table('ProjectAssignments')
    op.drop_index(op.f('ix_Notifications_user_id'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_type'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_is_read'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_entity_type'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_entity_id'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_created_at'), table_name='Notifications')
    op.drop_table('Notifications')
    op.drop_index(op.f('ix_Applications_owner_id'), table_name='Applications')
    op.drop_index(op.f('ix_Applications_name'), table_name='Applications')
    op.drop_table('Applications')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_TaskStatuses_project_id'), table_name='TaskStatuses')
    op.drop_table('TaskStatuses')
    op.drop_index(op.f('ix_Projects_project_owner_user_id'), table_name='Projects')
    op.drop_index(op.f('ix_Projects_override_status_id'), table_name='Projects')
    op.drop_index(op.f('ix_Projects_override_by_user_id'), table_name='Projects')
    op.drop_index(op.f('ix_Projects_name'), table_name='Projects')
    op.drop_index(op.f('ix_Projects_key'), table_name='Projects')
    op.drop_index(op.f('ix_Projects_derived_status_id'), table_name='Projects')
    op.drop_index(op.f('ix_Projects_created_by'), table_name='Projects')
    op.drop_index(op.f('ix_Projects_application_id'), table_name='Projects')
    op.drop_table('Projects')
    # ### end Alembic commands ###
