"""Image understanding service for vision LLM processing.

Processes images embedded in TipTap documents and imported documents through
a vision LLM to generate text descriptions. Descriptions are stored as
supplementary DocumentChunks for RAG retrieval, enabling semantic search
over visual content that would otherwise be invisible to text-based
embeddings.

TipTap images are detected by walking the JSON content tree for
``image`` nodes with ``attachmentId`` attrs. Imported images
(from Docling) are uploaded to MinIO first, then described.

Rate limits:
- Max 10 images per document (position-ordered, excess logged)
- Images < 10KB skipped (likely icons/bullets)
- Sequential processing to avoid overwhelming vision API
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass
from typing import Any
from uuid import UUID

import tiktoken
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from ..models.attachment import Attachment
from ..models.document_chunk import DocumentChunk
from ..services.minio_service import MinIOService
from .embedding_normalizer import EmbeddingNormalizer
from .embedding_service import EmbeddingService
from .provider_interface import VisionProvider
from .provider_registry import ConfigurationError, ProviderRegistry

logger = logging.getLogger(__name__)

# Vision prompt used for all image descriptions
_VISION_PROMPT = (
    "Describe exactly what is shown in this image. Be concise and factual. "
    "Include all visible text, labels, data, names, and UI elements. "
    "Do not add commentary, suggestions, or offers to help."
)

# Processing limits
from .config_service import get_agent_config as _get_agent_config
_MAX_IMAGES_PER_DOCUMENT = _get_agent_config().get_int("embedding.max_images_per_document", 10)
_MIN_IMAGE_SIZE_BYTES = 10 * 1024  # 10KB
_VISION_TIMEOUT_S = 30  # Per-image vision API timeout


@dataclass
class ImageDescription:
    """Result of describing a single image via vision LLM.

    Attributes:
        attachment_id: UUID of the existing Attachment record, if from a
            TipTap document image. None for imported images that have not
            yet been persisted.
        image_index: Position of the image within the document (0-based).
        description: Text description generated by the vision LLM.
        token_count: Token count of the final chunk text (for embedding).
    """

    attachment_id: UUID | None
    image_index: int
    description: str
    token_count: int


@dataclass
class ExtractedImage:
    """Image extracted from an imported document (e.g. by Docling).

    This dataclass is defined here as the canonical contract for Phase 6
    document import integration. Importers populate instances and pass
    them to ``process_imported_images``.

    Attributes:
        data: Raw image bytes.
        content_type: MIME type (e.g. ``image/png``).
        filename: Suggested filename for MinIO storage.
        caption: Alt text or caption extracted from the source document.
        page_number: Source page number (for PDFs), or 0 if not applicable.
    """

    data: bytes
    content_type: str
    filename: str
    caption: str
    page_number: int


class ImageUnderstandingService:
    """Processes images through vision LLM and stores descriptions as chunks.

    Handles two image sources:
    1. **TipTap documents**: Walks the JSON content tree, finds
       ``image`` nodes, downloads from MinIO, describes via
       VisionProvider, and stores supplementary DocumentChunks.
    2. **Imported documents**: Receives pre-extracted images, uploads to
       MinIO as Attachment records, describes, and stores chunks.

    Args:
        provider_registry: Factory for resolving the vision LLM provider.
        embedding_service: Service for generating chunk embeddings.
        minio_service: MinIO file operations client.
        db: Async database session.
    """

    def __init__(
        self,
        provider_registry: ProviderRegistry,
        embedding_service: EmbeddingService,
        minio_service: MinIOService,
        db: AsyncSession,
    ) -> None:
        self.provider_registry = provider_registry
        self.embedding_service = embedding_service
        self.minio_service = minio_service
        self.db = db
        self._encoder = tiktoken.get_encoding("cl100k_base")  # tiktoken caches internally

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def process_document_images(
        self,
        document_id: UUID,
        content_json: dict[str, Any],
    ) -> list[ImageDescription]:
        """Process images embedded in a TipTap document.

        Pipeline:
        1. Walk TipTap JSON content tree.
        2. Find nodes with ``type='image'`` and ``attrs.attachmentId``.
        3. For each image (max 10, position order):
           a. Look up Attachment record in DB.
           b. Download bytes from MinIO.
           c. Skip if < 10KB.
           d. Send to VisionProvider.describe_image().
           e. Create ImageDescription.
        4. Store descriptions as supplementary DocumentChunks.
        5. Generate embeddings for the new chunks.

        Args:
            document_id: UUID of the parent document.
            content_json: Parsed TipTap JSON content dict.

        Returns:
            List of ImageDescription for successfully processed images.
        """
        start_time = time.monotonic()

        # Step 1-2: Extract image nodes from TipTap tree
        image_nodes = self._extract_image_nodes(content_json)
        total_found = len(image_nodes)

        if not image_nodes:
            logger.debug("No images found in document %s", document_id)
            return []

        # Enforce max images limit
        if total_found > _MAX_IMAGES_PER_DOCUMENT:
            logger.warning(
                "Document %s has %d images, processing only first %d",
                document_id,
                total_found,
                _MAX_IMAGES_PER_DOCUMENT,
            )
            image_nodes = image_nodes[:_MAX_IMAGES_PER_DOCUMENT]

        # Resolve vision provider (early exit if unavailable)
        vision_provider, vision_model = await self._get_vision_provider()
        if vision_provider is None:
            return []

        # Step 3: Process each image sequentially
        descriptions: list[ImageDescription] = []
        skipped_small = 0
        failed = 0
        total_vision_ms = 0

        for idx, node_info in enumerate(image_nodes):
            attachment_id = node_info["attachment_id"]
            caption = node_info.get("alt") or node_info.get("title") or ""

            try:
                # 3a: Look up Attachment record
                attachment = await self._get_attachment(attachment_id)
                if attachment is None:
                    logger.warning(
                        "Attachment %s not found for document %s image %d, skipping",
                        attachment_id,
                        document_id,
                        idx,
                    )
                    failed += 1
                    continue

                # 3b: Download from MinIO
                image_bytes = await self._download_image(attachment)
                if image_bytes is None:
                    logger.warning(
                        "Failed to download attachment %s from MinIO for document %s, skipping",
                        attachment_id,
                        document_id,
                    )
                    failed += 1
                    continue

                # 3c: Skip small images
                if len(image_bytes) < _MIN_IMAGE_SIZE_BYTES:
                    logger.debug(
                        "Skipping image %s (%d bytes < %d threshold)",
                        attachment_id,
                        len(image_bytes),
                        _MIN_IMAGE_SIZE_BYTES,
                    )
                    skipped_small += 1
                    continue

                # 3d: Describe via vision LLM (with timeout)
                vision_start = time.monotonic()
                try:
                    description_text = await asyncio.wait_for(
                        self._describe_image(
                            vision_provider, vision_model, image_bytes
                        ),
                        timeout=_VISION_TIMEOUT_S,
                    )
                except asyncio.TimeoutError:
                    logger.warning(
                        "Vision LLM timeout for image %d in document %s",
                        idx,
                        document_id,
                    )
                    failed += 1
                    continue
                vision_elapsed = int((time.monotonic() - vision_start) * 1000)
                total_vision_ms += vision_elapsed

                if not description_text or not description_text.strip():
                    logger.warning(
                        "Vision LLM returned empty description for attachment %s",
                        attachment_id,
                    )
                    failed += 1
                    continue

                # 3e: Build chunk text and create ImageDescription
                chunk_text = self._build_chunk_text(caption, description_text)
                token_count = self._count_tokens(chunk_text)

                descriptions.append(ImageDescription(
                    attachment_id=attachment_id,
                    image_index=idx,
                    description=description_text,
                    token_count=token_count,
                ))

            except Exception:
                logger.exception(
                    "Error processing image %d (attachment %s) in document %s",
                    idx,
                    attachment_id,
                    document_id,
                )
                failed += 1

        # Log metrics
        elapsed_total = int((time.monotonic() - start_time) * 1000)
        logger.info(
            "Image processing for document %s: found=%d, skipped_small=%d, "
            "processed=%d, failed=%d, vision_api_ms=%d, total_ms=%d",
            document_id,
            total_found,
            skipped_small,
            len(descriptions),
            failed,
            total_vision_ms,
            elapsed_total,
        )

        if not descriptions:
            return []

        # Step 4-5: Store as supplementary DocumentChunks with embeddings
        await self._store_image_chunks(
            document_id=document_id,
            descriptions=descriptions,
            image_nodes=image_nodes,
        )

        return descriptions

    async def process_imported_images(
        self,
        images: list[ExtractedImage],
        document_id: UUID,
        scope_ids: dict[str, Any],
        slide_titles: dict[int, str] | None = None,
    ) -> list[ImageDescription]:
        """Process images extracted by Docling from imported documents.

        Pipeline:
        1. Upload each image to MinIO as an Attachment record.
        2. Send to VisionProvider for description.
        3. Create supplementary DocumentChunks with descriptions.
        4. Generate embeddings for the new chunks.

        Args:
            images: List of ExtractedImage from the document importer.
            document_id: UUID of the parent document.
            scope_ids: Dict with ``application_id``, ``project_id``,
                ``user_id`` for denormalized chunk scope.

        Returns:
            List of ImageDescription for successfully processed images.
        """
        start_time = time.monotonic()

        if not images:
            return []

        total_found = len(images)

        # Enforce max images limit
        if total_found > _MAX_IMAGES_PER_DOCUMENT:
            logger.warning(
                "Imported document %s has %d images, processing only first %d",
                document_id,
                total_found,
                _MAX_IMAGES_PER_DOCUMENT,
            )
            images = images[:_MAX_IMAGES_PER_DOCUMENT]

        # Resolve vision provider
        vision_provider, vision_model = await self._get_vision_provider()
        if vision_provider is None:
            return []

        descriptions: list[ImageDescription] = []
        skipped_small = 0
        failed = 0
        total_vision_ms = 0

        for idx, image in enumerate(images):
            try:
                # Skip small images
                if len(image.data) < _MIN_IMAGE_SIZE_BYTES:
                    logger.debug(
                        "Skipping imported image %d (%d bytes < %d threshold)",
                        idx,
                        len(image.data),
                        _MIN_IMAGE_SIZE_BYTES,
                    )
                    skipped_small += 1
                    continue

                # Step 1: Upload to MinIO and create Attachment record
                attachment = await self._upload_imported_image(
                    image=image,
                    document_id=document_id,
                    uploaded_by=scope_ids.get("user_id"),
                )

                # Step 2: Describe via vision LLM (with timeout)
                vision_start = time.monotonic()
                try:
                    description_text = await asyncio.wait_for(
                        self._describe_image(
                            vision_provider, vision_model, image.data
                        ),
                        timeout=_VISION_TIMEOUT_S,
                    )
                except asyncio.TimeoutError:
                    logger.warning(
                        "Vision LLM timeout for imported image %d in document %s",
                        idx,
                        document_id,
                    )
                    failed += 1
                    continue
                vision_elapsed = int((time.monotonic() - vision_start) * 1000)
                total_vision_ms += vision_elapsed

                if not description_text or not description_text.strip():
                    logger.warning(
                        "Vision LLM returned empty description for imported image %d",
                        idx,
                    )
                    failed += 1
                    continue

                # Build chunk text
                caption = image.caption or ""
                chunk_text = self._build_chunk_text(caption, description_text)
                token_count = self._count_tokens(chunk_text)

                descriptions.append(ImageDescription(
                    attachment_id=attachment.id,
                    image_index=idx,
                    description=description_text,
                    token_count=token_count,
                ))

            except Exception:
                logger.exception(
                    "Error processing imported image %d in document %s",
                    idx,
                    document_id,
                )
                failed += 1

        # Log metrics
        elapsed_total = int((time.monotonic() - start_time) * 1000)
        logger.info(
            "Imported image processing for document %s: found=%d, skipped_small=%d, "
            "processed=%d, failed=%d, vision_api_ms=%d, total_ms=%d",
            document_id,
            total_found,
            skipped_small,
            len(descriptions),
            failed,
            total_vision_ms,
            elapsed_total,
        )

        if not descriptions:
            return []

        # Step 3-4: Store as supplementary DocumentChunks with embeddings
        # Build heading context list (page/slide context for imports)
        image_nodes_for_chunks: list[dict[str, Any]] = []
        for idx_d, desc in enumerate(descriptions):
            img = images[desc.image_index]
            slide_title = (slide_titles or {}).get(img.page_number) if img.page_number else None
            if slide_title:
                heading = f"Imported Image — Slide {img.page_number}: {slide_title}"
            elif img.page_number:
                heading = f"Imported Image (page {img.page_number})"
            else:
                heading = "Imported Image"
            image_nodes_for_chunks.append({
                "heading_context": heading,
                "alt": img.caption,
                "title": "",
            })

        await self._store_image_chunks(
            document_id=document_id,
            descriptions=descriptions,
            image_nodes=image_nodes_for_chunks,
            scope_ids=scope_ids,
        )

        return descriptions

    # ------------------------------------------------------------------
    # TipTap tree walking
    # ------------------------------------------------------------------

    def _extract_image_nodes(
        self,
        content_json: dict[str, Any],
    ) -> list[dict[str, Any]]:
        """Walk TipTap JSON tree and extract image nodes.

        Returns a list of dicts, each containing:
        - ``attachment_id``: UUID of the linked Attachment.
        - ``heading_context``: Nearest ancestor heading text (or None).
        - ``alt``: Alt text from the node attrs.
        - ``title``: Title from the node attrs.

        Nodes are returned in document order (position order).
        """
        results: list[dict[str, Any]] = []
        nodes = content_json.get("content", [])
        if not nodes:
            return results

        self._walk_tiptap_nodes(nodes, current_heading=None, results=results)
        return results

    def _walk_tiptap_nodes(
        self,
        nodes: list[dict[str, Any]],
        current_heading: str | None,
        results: list[dict[str, Any]],
    ) -> str | None:
        """Recursively walk TipTap nodes to find image nodes.

        Updates ``results`` in-place with found image nodes.
        Returns the current heading context after processing all nodes.

        Args:
            nodes: List of TipTap child nodes.
            current_heading: Current heading context from ancestors.
            results: Accumulator list (mutated in place).

        Returns:
            Updated heading context string.
        """
        for node in nodes:
            node_type = node.get("type", "")

            if node_type == "heading":
                # Update heading context for subsequent nodes
                heading_text = self._inline_text(node.get("content", []))
                if heading_text.strip():
                    current_heading = heading_text.strip()

            elif node_type == "image":
                attrs = node.get("attrs", {})
                attachment_id_str = attrs.get("attachmentId")
                if attachment_id_str:
                    try:
                        attachment_id = UUID(str(attachment_id_str))
                        results.append({
                            "attachment_id": attachment_id,
                            "heading_context": current_heading,
                            "alt": attrs.get("alt", "") or "",
                            "title": attrs.get("title", "") or "",
                        })
                    except (ValueError, AttributeError):
                        logger.warning(
                            "Invalid attachmentId in image node: %s",
                            attachment_id_str,
                        )

            # Recurse into children
            children = node.get("content", [])
            if children:
                current_heading = self._walk_tiptap_nodes(
                    children, current_heading, results
                )

        return current_heading

    @staticmethod
    def _inline_text(nodes: list[dict[str, Any]]) -> str:
        """Extract inline text from TipTap text/hardBreak nodes."""
        parts: list[str] = []
        for node in nodes:
            if node.get("type") == "text":
                parts.append(node.get("text", ""))
            elif node.get("type") == "hardBreak":
                parts.append("\n")
        return "".join(parts)

    # ------------------------------------------------------------------
    # Image download & description
    # ------------------------------------------------------------------

    async def _get_vision_provider(
        self,
    ) -> tuple[VisionProvider | None, str]:
        """Resolve the vision provider, returning (None, "") if unavailable."""
        try:
            provider, model = await self.provider_registry.get_vision_provider(self.db)
            return provider, model
        except ConfigurationError:
            logger.warning(
                "No vision provider configured. Image understanding disabled."
            )
            return None, ""

    async def _get_attachment(self, attachment_id: UUID) -> Attachment | None:
        """Look up an Attachment record by ID."""
        result = await self.db.execute(
            select(Attachment).where(Attachment.id == attachment_id)
        )
        return result.scalar_one_or_none()

    async def _download_image(self, attachment: Attachment) -> bytes | None:
        """Download image bytes from MinIO using the Attachment record.

        Returns None if the attachment has no MinIO reference or download fails.
        Uses asyncio.to_thread to avoid blocking the event loop.
        """
        import asyncio

        if not attachment.minio_bucket or not attachment.minio_key:
            logger.warning(
                "Attachment %s has no MinIO reference (bucket=%s, key=%s)",
                attachment.id,
                attachment.minio_bucket,
                attachment.minio_key,
            )
            return None

        try:
            return await asyncio.to_thread(
                self.minio_service.download_file,
                attachment.minio_bucket,
                attachment.minio_key,
            )
        except Exception:
            logger.exception(
                "MinIO download failed for attachment %s (bucket=%s, key=%s)",
                attachment.id,
                attachment.minio_bucket,
                attachment.minio_key,
            )
            return None

    async def _describe_image(
        self,
        provider: VisionProvider,
        model: str,
        image_bytes: bytes,
    ) -> str:
        """Send image bytes to the vision provider for description.

        Args:
            provider: Resolved VisionProvider instance.
            model: Vision model identifier string.
            image_bytes: Raw image data.

        Returns:
            Description text from the vision LLM, or empty string on failure.
        """
        try:
            return await provider.describe_image(
                image_bytes=image_bytes,
                prompt=_VISION_PROMPT,
                model=model,
            )
        except Exception:
            logger.exception("Vision LLM describe_image call failed")
            return ""

    # ------------------------------------------------------------------
    # Chunk storage
    # ------------------------------------------------------------------

    async def _store_image_chunks(
        self,
        document_id: UUID,
        descriptions: list[ImageDescription],
        image_nodes: list[dict[str, Any]],
        scope_ids: dict[str, Any] | None = None,
    ) -> None:
        """Store image descriptions as supplementary DocumentChunks.

        Image chunks are appended after existing text chunks. The chunk_index
        is offset by the current maximum chunk_index for the document + 1,
        so image chunks never collide with text chunks.

        Also generates embeddings for the new chunks via the EmbeddingService's
        provider.

        Args:
            document_id: Parent document UUID.
            descriptions: Successfully processed ImageDescription list.
            image_nodes: Parallel list of node info dicts (for heading_context).
            scope_ids: Optional scope dict. If None, scope is read from the
                first existing chunk for the document (for TipTap flow where
                the document already has text chunks).
        """
        if not descriptions:
            return

        # Determine chunk_index offset (append after existing text chunks)
        max_index_result = await self.db.execute(
            select(func.max(DocumentChunk.chunk_index)).where(
                DocumentChunk.document_id == document_id
            )
        )
        current_max = max_index_result.scalar()
        offset = (current_max + 1) if current_max is not None else 0

        # Resolve scope from existing chunks if not provided
        if scope_ids is None:
            scope_ids = await self._resolve_scope_from_chunks(document_id)

        # Generate embeddings for all description chunk texts
        chunk_texts = []
        for idx, desc in enumerate(descriptions):
            node_info = image_nodes[idx] if idx < len(image_nodes) else {}
            caption = node_info.get("alt") or node_info.get("title") or ""
            chunk_text = self._build_chunk_text(caption, desc.description)
            chunk_texts.append(chunk_text)

        embeddings = await self._generate_embeddings(chunk_texts)

        # Create DocumentChunk records
        new_chunks: list[DocumentChunk] = []
        for idx, desc in enumerate(descriptions):
            node_info = image_nodes[idx] if idx < len(image_nodes) else {}
            heading_context = node_info.get("heading_context")
            caption = node_info.get("alt") or node_info.get("title") or ""
            chunk_text = self._build_chunk_text(caption, desc.description)

            embedding = embeddings[idx] if idx < len(embeddings) else None

            chunk = DocumentChunk(
                document_id=document_id,
                chunk_index=offset + idx,
                chunk_text=chunk_text,
                chunk_type="image",
                heading_context=heading_context,
                embedding=embedding,
                token_count=desc.token_count,
                application_id=scope_ids.get("application_id"),
                project_id=scope_ids.get("project_id"),
                user_id=scope_ids.get("user_id"),
            )
            new_chunks.append(chunk)

        self.db.add_all(new_chunks)
        await self.db.flush()

        logger.info(
            "Stored %d image description chunks for document %s (chunk_index %d-%d)",
            len(new_chunks),
            document_id,
            offset,
            offset + len(new_chunks) - 1,
        )

    async def _resolve_scope_from_chunks(
        self, document_id: UUID
    ) -> dict[str, Any]:
        """Read scope IDs from the first existing chunk for a document.

        Falls back to empty scope if no chunks exist (image-only documents
        will have scope set by the caller).
        """
        result = await self.db.execute(
            select(
                DocumentChunk.application_id,
                DocumentChunk.project_id,
                DocumentChunk.user_id,
            )
            .where(DocumentChunk.document_id == document_id)
            .limit(1)
        )
        row = result.first()
        if row is not None:
            return {
                "application_id": row.application_id,
                "project_id": row.project_id,
                "user_id": row.user_id,
            }
        return {"application_id": None, "project_id": None, "user_id": None}

    async def _generate_embeddings(
        self, texts: list[str]
    ) -> list[list[float] | None]:
        """Generate normalized embeddings for a list of chunk texts.

        Returns a list parallel to ``texts``. On failure, returns a list
        of None values (chunks are still stored without embeddings so they
        can be embedded later during a reindex).
        """
        if not texts:
            return []

        try:
            provider, model_id = await self.provider_registry.get_embedding_provider(
                self.db
            )
            raw_embeddings = await provider.generate_embeddings_batch(texts, model_id)
            normalizer = EmbeddingNormalizer()
            return [normalizer.normalize(emb) for emb in raw_embeddings]
        except Exception:
            logger.exception(
                "Failed to generate embeddings for %d image chunks, "
                "storing chunks without embeddings",
                len(texts),
            )
            return [None] * len(texts)

    # ------------------------------------------------------------------
    # Imported image upload
    # ------------------------------------------------------------------

    async def _upload_imported_image(
        self,
        image: ExtractedImage,
        document_id: UUID,
        uploaded_by: UUID | None,
    ) -> Attachment:
        """Upload an imported image to MinIO and create an Attachment record.

        Args:
            image: ExtractedImage with raw data and metadata.
            document_id: Parent document UUID (used as entity_id).
            uploaded_by: UUID of the user who triggered the import.

        Returns:
            Created Attachment ORM instance (flushed, has id).
        """
        import asyncio

        bucket = await asyncio.to_thread(
            self.minio_service.get_bucket_for_content_type, image.content_type
        )
        object_name = await asyncio.to_thread(
            self.minio_service.generate_object_name,
            "document",
            str(document_id),
            image.filename,
        )

        await asyncio.to_thread(
            self.minio_service.upload_bytes,
            bucket,
            object_name,
            image.data,
            image.content_type,
        )

        attachment = Attachment(
            file_name=image.filename,
            file_type=image.content_type,
            file_size=len(image.data),
            minio_bucket=bucket,
            minio_key=object_name,
            entity_type="document",
            entity_id=document_id,
            uploaded_by=uploaded_by,
        )
        self.db.add(attachment)
        await self.db.flush()

        logger.debug(
            "Uploaded imported image as attachment %s (bucket=%s, key=%s, %d bytes)",
            attachment.id,
            bucket,
            object_name,
            len(image.data),
        )

        return attachment

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_chunk_text(caption: str, description: str) -> str:
        """Format the image description as a chunk text string.

        Format: ``[Image: {caption}] {description}``
        If caption is empty: ``[Image] {description}``
        """
        if caption and caption.strip():
            return f"[Image: {caption.strip()}] {description.strip()}"
        return f"[Image] {description.strip()}"

    def _count_tokens(self, text: str) -> int:
        """Count tokens using tiktoken cl100k_base encoding."""
        if not text:
            return 0
        return len(self._encoder.encode(text))
