"""Attachment SQLAlchemy model for file attachments stored in MinIO."""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import BigInteger, Column, DateTime, ForeignKey, String
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER
from sqlalchemy.orm import relationship

from ..database import Base

if TYPE_CHECKING:
    from .note import Note
    from .task import Task
    from .user import User


class Attachment(Base):
    """
    Attachment model representing files stored in MinIO object storage.

    Attachments use a polymorphic association pattern to link to different
    entity types (tasks, notes, comments). Files are stored in MinIO and
    referenced by bucket and key.

    Attributes:
        id: Unique identifier (UUID)
        file_name: Original file name
        file_type: MIME type of the file
        file_size: File size in bytes
        minio_bucket: MinIO bucket name
        minio_key: MinIO object key (path within bucket)
        uploaded_by: FK to user who uploaded the file
        entity_type: Type of entity this is attached to ('task', 'note', 'comment')
        entity_id: ID of the entity this is attached to
        task_id: Direct FK to task (when entity_type is 'task')
        note_id: Direct FK to note (when entity_type is 'note')
        created_at: Timestamp when attachment was created
    """

    __tablename__ = "Attachments"
    __allow_unmapped__ = True

    # Primary key - UUID generated by SQL Server
    id = Column(
        UNIQUEIDENTIFIER,
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # File metadata
    file_name = Column(
        String(255),
        nullable=False,
    )
    file_type = Column(
        String(100),
        nullable=True,
    )
    file_size = Column(
        BigInteger,
        nullable=True,
    )

    # MinIO storage reference
    minio_bucket = Column(
        String(100),
        nullable=True,
    )
    minio_key = Column(
        String(500),
        nullable=True,
    )

    # Polymorphic association fields
    entity_type = Column(
        String(50),
        nullable=True,
        index=True,
    )
    entity_id = Column(
        UNIQUEIDENTIFIER,
        nullable=True,
        index=True,
    )

    # Direct foreign keys for common entity types
    task_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Tasks.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    note_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Notes.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    uploaded_by = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Timestamps
    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    # Relationships
    task = relationship(
        "Task",
        back_populates="attachments",
        lazy="joined",
    )
    note = relationship(
        "Note",
        back_populates="attachments",
        lazy="joined",
        foreign_keys=[note_id],
    )
    uploader = relationship(
        "User",
        back_populates="uploaded_attachments",
        lazy="joined",
    )

    def __repr__(self) -> str:
        """String representation of Attachment."""
        return f"<Attachment(id={self.id}, file_name={self.file_name})>"
