"""Checklist SQLAlchemy model for task checklists."""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER
from sqlalchemy.orm import relationship

from ..database import Base

if TYPE_CHECKING:
    from .checklist_item import ChecklistItem
    from .task import Task


class Checklist(Base):
    """
    Checklist model for task checklists.

    Named checklist container belonging to a task with denormalized
    progress tracking for efficient display on task cards.

    Attributes:
        id: Unique identifier (UUID)
        task_id: FK to parent task
        title: Checklist name
        rank: Lexorank for ordering checklists within a task
        total_items: Denormalized item count
        completed_items: Denormalized completion count
        created_at: Timestamp when checklist was created
    """

    __tablename__ = "Checklists"
    __allow_unmapped__ = True

    # Primary key - UUID generated by SQL Server
    id = Column(
        UNIQUEIDENTIFIER,
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # Foreign keys
    task_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Checklist details
    title = Column(
        String(255),
        nullable=False,
    )
    rank = Column(
        String(50),
        nullable=False,
    )

    # Denormalized counts for efficient display
    total_items = Column(
        Integer,
        nullable=False,
        default=0,
    )
    completed_items = Column(
        Integer,
        nullable=False,
        default=0,
    )

    # Timestamps
    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    # Relationships
    task = relationship(
        "Task",
        back_populates="checklists",
        lazy="joined",
    )
    items = relationship(
        "ChecklistItem",
        back_populates="checklist",
        cascade="all, delete-orphan",
        order_by="ChecklistItem.rank",
        lazy="selectin",
    )

    @property
    def progress_text(self) -> str:
        """Return progress as 'completed/total' string."""
        return f"{self.completed_items}/{self.total_items}"

    @property
    def progress_percent(self) -> int:
        """Return progress as percentage (0-100)."""
        if self.total_items == 0:
            return 0
        return int((self.completed_items / self.total_items) * 100)

    def __repr__(self) -> str:
        """String representation of Checklist."""
        return f"<Checklist(id={self.id}, title={self.title}, progress={self.progress_text})>"
