"""ChecklistItem SQLAlchemy model for checklist items."""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import Column, DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.mssql import BIT, UNIQUEIDENTIFIER
from sqlalchemy.orm import relationship

from ..database import Base

if TYPE_CHECKING:
    from .checklist import Checklist
    from .user import User


class ChecklistItem(Base):
    """
    ChecklistItem model for individual checklist items.

    Supports completion tracking with who completed and when.

    Attributes:
        id: Unique identifier (UUID)
        checklist_id: FK to parent checklist
        content: Item text content
        is_done: Completion status
        completed_by: FK to user who completed the item
        completed_at: Timestamp when item was completed
        rank: Lexorank for ordering items within a checklist
        created_at: Timestamp when item was created
        updated_at: Timestamp when item was last updated
    """

    __tablename__ = "ChecklistItems"
    __allow_unmapped__ = True

    # Primary key - UUID generated by SQL Server
    id = Column(
        UNIQUEIDENTIFIER,
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # Foreign keys
    checklist_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Checklists.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    completed_by = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Users.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Content
    content = Column(
        Text,
        nullable=False,
    )

    # Completion status
    is_done = Column(
        BIT,
        nullable=False,
        default=False,
    )
    completed_at = Column(
        DateTime,
        nullable=True,
    )

    # Ordering
    rank = Column(
        String(50),
        nullable=False,
    )

    # Timestamps
    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )
    updated_at = Column(
        DateTime,
        nullable=True,
    )

    # Relationships
    checklist = relationship(
        "Checklist",
        back_populates="items",
        lazy="joined",
    )
    completer = relationship(
        "User",
        lazy="joined",
    )

    def toggle(self, user_id: Optional[str] = None) -> None:
        """
        Toggle completion status.

        Args:
            user_id: UUID of user toggling the item (required when completing)
        """
        if self.is_done:
            self.is_done = False
            self.completed_by = None
            self.completed_at = None
        else:
            self.is_done = True
            self.completed_by = user_id
            self.completed_at = datetime.utcnow()
        self.updated_at = datetime.utcnow()

    def __repr__(self) -> str:
        """String representation of ChecklistItem."""
        status = "done" if self.is_done else "pending"
        preview = self.content[:30] if self.content else "No content"
        return f"<ChecklistItem(id={self.id}, status={status}, content={preview})>"
