"""Comment SQLAlchemy model for task comments."""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import Column, DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.mssql import BIT, UNIQUEIDENTIFIER
from sqlalchemy.orm import relationship

from ..database import Base

if TYPE_CHECKING:
    from .attachment import Attachment
    from .mention import Mention
    from .task import Task
    from .user import User


class Comment(Base):
    """
    Comment model for task discussions.

    Stores user comments on tasks with rich text content (TipTap JSON)
    and supports soft delete for audit trail.

    Attributes:
        id: Unique identifier (UUID)
        task_id: FK to parent task
        author_id: FK to user who created the comment
        body_json: TipTap JSON content for rich text rendering
        body_text: Plain text extracted for full-text search
        is_deleted: Soft delete flag
        created_at: Timestamp when comment was created
        updated_at: Timestamp when comment was last updated
    """

    __tablename__ = "Comments"
    __allow_unmapped__ = True

    # Primary key - UUID generated by SQL Server
    id = Column(
        UNIQUEIDENTIFIER,
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # Foreign keys
    task_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    author_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Users.id", ondelete="SET NULL"),
        nullable=False,
        index=True,
    )

    # Content fields
    body_json = Column(
        Text,
        nullable=True,
    )
    body_text = Column(
        Text,
        nullable=True,
    )

    # Soft delete flag
    is_deleted = Column(
        BIT,
        nullable=False,
        default=False,
    )

    # Timestamps
    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )
    updated_at = Column(
        DateTime,
        nullable=True,
    )

    # Relationships
    task = relationship(
        "Task",
        back_populates="comments",
        lazy="joined",
    )
    author = relationship(
        "User",
        lazy="joined",
    )
    mentions = relationship(
        "Mention",
        back_populates="comment",
        cascade="all, delete-orphan",
        lazy="selectin",
    )
    attachments = relationship(
        "Attachment",
        back_populates="comment",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        """String representation of Comment."""
        preview = self.body_text[:30] if self.body_text else "No content"
        return f"<Comment(id={self.id}, task_id={self.task_id}, preview={preview})>"
