"""Project SQLAlchemy model for project management."""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List

from sqlalchemy import Column, DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER
from sqlalchemy.orm import relationship

from ..database import Base

if TYPE_CHECKING:
    from .application import Application
    from .project_assignment import ProjectAssignment
    from .task import Task


class Project(Base):
    """
    Project model representing projects within an application.

    Projects are part of the hierarchy: Application > Projects > Tasks

    Attributes:
        id: Unique identifier (UUID)
        application_id: FK to parent application
        name: Project name
        key: Short project key for task prefixes (e.g., "PROJ")
        description: Optional project description
        project_type: Type of project (scrum, kanban, etc.)
        created_at: Timestamp when project was created
        updated_at: Timestamp when project was last updated
    """

    __tablename__ = "Projects"
    __allow_unmapped__ = True

    # Primary key - UUID generated by SQL Server
    id = Column(
        UNIQUEIDENTIFIER,
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # Foreign keys
    application_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Applications.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Project details
    name = Column(
        String(255),
        nullable=False,
        index=True,
    )
    key = Column(
        String(10),
        nullable=False,
        index=True,
    )
    description = Column(
        Text,
        nullable=True,
    )
    project_type = Column(
        String(50),
        nullable=True,
        default="kanban",
    )

    # Timestamps
    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )
    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    # Relationships
    application = relationship(
        "Application",
        back_populates="projects",
        lazy="joined",
    )
    tasks = relationship(
        "Task",
        back_populates="project",
        cascade="all, delete-orphan",
        lazy="dynamic",
    )
    assignments = relationship(
        "ProjectAssignment",
        back_populates="project",
        cascade="all, delete-orphan",
        lazy="dynamic",
    )

    def __repr__(self) -> str:
        """String representation of Project."""
        return f"<Project(id={self.id}, key={self.key}, name={self.name})>"
