"""ProjectMember SQLAlchemy model for project team gate permissions."""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import Column, DateTime, ForeignKey, UniqueConstraint
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER
from sqlalchemy.orm import relationship

from ..database import Base

if TYPE_CHECKING:
    from .project import Project
    from .user import User


class ProjectMember(Base):
    """
    ProjectMember model representing user membership in project teams.

    ProjectMembers act as a "gate" for project-level permissions. Editors
    must be ProjectMembers to create, edit, or move tasks within a project.
    This is separate from ProjectAssignment which tracks work assignments.

    Key differences from ProjectAssignment:
    - ProjectAssignments: who is assigned to work on the project
    - ProjectMembers: who has PERMISSION to manage tasks (gate for Editors)

    Attributes:
        id: Unique identifier (UUID)
        project_id: FK to the project
        user_id: FK to the member user
        added_by_user_id: FK to the user who added this member (optional)
        created_at: Timestamp when membership was created
    """

    __tablename__ = "ProjectMembers"
    __allow_unmapped__ = True

    # Unique constraint on project_id + user_id
    __table_args__ = (
        UniqueConstraint(
            "project_id",
            "user_id",
            name="UQ_ProjectMembers_Project_User",
        ),
    )

    # Primary key - UUID generated by SQL Server
    id = Column(
        UNIQUEIDENTIFIER,
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # Foreign keys
    project_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    added_by_user_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("Users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Timestamps
    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True,
    )

    # Relationships
    # Note: back_populates will be added to Project and User models
    # when their relationships are extended in a subsequent subtask
    project = relationship(
        "Project",
        lazy="joined",
    )
    user = relationship(
        "User",
        foreign_keys=[user_id],
        lazy="joined",
    )
    added_by = relationship(
        "User",
        foreign_keys=[added_by_user_id],
        lazy="joined",
    )

    def __repr__(self) -> str:
        """String representation of ProjectMember."""
        return f"<ProjectMember(id={self.id}, project_id={self.project_id}, user_id={self.user_id})>"
